### ISSUE TITLE
Fix the spelling mistakes.

### ISSUE THREAD

**Issue by setco-website** [setco-website/git-verse#1]
There are so many mistakes here. Someone please fix it.

**Comment by sasuke2003sr** [comment]
I understand the problem that you have been working on.
I also see that the subjects also have some mistakes.

**Comment by setco-website** [comment]
Thanks, that's a good catch. The issue is all yours to solve.

**Comment by SweetyPandey789** [comment]
Hey !
I got your issues and i can solve your issues and I would be the right person to fix.

**Comment by SweetyPandey789** [comment]
Hey !
I got your issues and i can solve your issues and I would be the right person to fix.
